### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by yehx1** [AIGCT/EASYChatGPT#1]
Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at D:\ProgramData\Anaconda3\lib\site-packages\playwright\_impl\_wait_helper.py:83> exception=CancelledError()>
concurrent.futures._base.CancelledError

I found this error. And If I terminate proxy, the browser keep restarting again and again.

**Comment by ITerydh** [comment]
> I found this error. And If I terminate proxy, the browser keep restarting again and again.

You need to quickly close the proxy after connecting to openai.
It's only possible to succeed. QAQ
